# Generated by Django 3.0.1 on 2020-02-01 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_auto_20200201_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersystem',
            name='friend',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_system', to=settings.AUTH_USER_MODEL),
        ),
    ]
