# Generated by Django 3.0.1 on 2020-02-01 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0004_auto_20200201_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersystem',
            name='friend',
            field=models.ManyToManyField(related_name='following_system', to=settings.AUTH_USER_MODEL),
        ),
    ]
